title: "Association for Computing Machinery (ACM) UMDearborn"
description: "Hands-on Workshop on Building Research Mindset and Skills through Reproducibility"
theme: jekyll-theme-cayman   # You can change the theme later if you like
